### ISSUE TITLE
questions about cholesky decompositon

### ISSUE THREAD

**Issue by BenjaminDai** [qm1900/parallelDMD#1]
Hello, Dalao,
      In dmd_mpi.cpp line 100-115, you use cholesky decomposition to (X'X) and get the upper triangular matrix r = cholesky.matrixU( ), assuming X=snapshotsProc.block(0, 0 , xnProc, tn). Then you conduct svd to r. I haven't seen this method elsewhere. In cfd literatures, svd was done directly to X, without extra treatment. I have tested the difference between this two methods in MATLAB, and the results indicate that the singular values are the same, while the left singular matrix and right singular matrix may have be different. Can you give me some explanation or any references on the method you used in your code? Thanks.

**Comment by qm1900** [comment]
Hi @BenjaminDai,  I did this code years ago for practice, and it might not be a very good code.  SVD can give different unitary matrices. Those operations are considered to facilitate parallel realisation, r has a very small rank so it is easy to SVD it in serial. Hope this can solve your questions, GL

**Comment by BenjaminDai** [comment]
Thanks for your answer
